### ISSUE TITLE
Dying and resetting does not reset meat stock amount.

### ISSUE THREAD

**Issue by Sporial** [Sporial/WarriorChef_Game#3]
**Describe the bug**

Dying and resetting the level does not reset meat stock of the player

**Version**
Version 4

**To Reproduce**
1. Get meat
2. Die
3. Select reset level
4. Maintain meatstock

**Expected behavior**
 Meatstock should be reset if the player is resetting the level. If the player is loading, meatstock should be loaded at the amount it was at when saved.

**Screenshots**

**Desktop System (please complete the following information):**
- OS: [e.g. Windows10, Windows8.1, MacOSX]
Win10

**Additional context**

**Comment by KyleLannen** [comment]
Problem fixed; 'startMeat' var added to SaveController script; Value is assigned when the scene is loaded. If the player dies and resets, meat will get reset to whatever it was at the start of the level.
