### ISSUE TITLE
Map Buttons not selectable after Level 3

### ISSUE THREAD

**Issue by Sporial** [Sporial/WarriorChef_Game#7]
**Describe the bug**

Upon completing level 3, none of the map buttons may be selected. Pressing 'Escape' may return to level 2

**Version**
v004
**To Reproduce**
 Complete lvl3

**Expected behavior**
Should probably be able to return to town or previous levels

**Desktop System (please complete the following information):**
Win10

**Additional context**

**Comment by KyleLannen** [comment]
Problem fixed; Order of map canvas was above the pause menu canvas, pausing made buttons non-functional until unpaused.
