### ISSUE TITLE
Assigning upgrade tokens to damage does not remove them nor increase damage

### ISSUE THREAD

**Issue by Sporial** [Sporial/WarriorChef_Game#8]
**Describe the bug**
Damage allocation seems to be completely broken. Upon returning to the upgrade menu at a later date, the upgrade tokens assigned to damage have not been consumed

**Version**
v004

**To Reproduce**
Cook upgrade tokens, apply upgrade tokens, return to game, cook more upgrade tokens, note upgrade tokens under damage still remain

**Expected behavior**
Upgrade tokens should be consumed in the same way they are for health -> applying upgrade should consume them and give relevant buff.

**Desktop System (please complete the following information):**
Win10

**Comment by KyleLannen** [comment]
Tokens get consumed, ez fix
