### ISSUE TITLE
Player 'New Game' function and spawning issue

### ISSUE THREAD

**Issue by Thelastone668** [Sporial/WarriorChef_Game#9]
**Describe the bug**

In the latest, unreleased version of the game, the player cannot select 'New Game' from the start menu. When the player is capable of selecting New Game, after commenting out a line of code within the PlayerController, they do not spawn in the proper place where the level is. 

**Version**
- Alpha v.5 (yet to be released), more accurately could be called Alpha v.4.5

**To Reproduce**
The Bug appears to be reproduced whenever the game is build from the project. What exactly seems to cause this is unknown. Though it appears to be linked in some way to the PlayerController Script and the NewGame function within, according to Kyle, one of our programmers.

When commenting it out, the game does load, however it introduces new problems such as the player not spawning onto the level. Instead spawning into the abyss. Additionally, this appears to only happen within the build of the game itself. The editor does not appear to have this problem.

**Expected behavior**
What was expected to happen was that the game would run without any issues. The player could click the play button and begin playing. However this does not appear to be the case. Any attempts to fix it thus far have not been fruitful.

**Screenshots**
N/A

**Desktop System (please complete the following information):**
- Windows

**Additional context**
This does not seem to be a problem with the game within the program of Unity, but more-so it appears to be a 'build' issue.

**Comment by Sporial** [comment]
Solved - an erroneous tag caused issues that are different in the editor version vs the build version.
